In [3]:
import numpy as np

In [186]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [ ]:
# How many negative numbers are there?  --4

In [5]:
a[a <0] # *** .size will pull the numeric value***

array([-2, -1, -6, -7])

In [ ]:
# How many positive numbers are there?  --5

In [6]:
a[a>0]

array([ 4, 10, 12, 23,  3])

In [ ]:
# How many even positive numbers are there? --3

In [66]:
a[(a>0) & (a % 2 == 0)]

array([ 4, 10, 12])

In [9]:
# If you were to add 3 to each data point, how many positive numbers would there be? --10

In [14]:
new = a + 3

In [64]:
new[new>0]

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3,  6])

In [16]:
# If you squared each number, what would the new mean and standard deviation be?

In [24]:
squared = np.square(a)

In [25]:
squared

array([ 16, 100, 144, 529,   4,   1,   0,   0,   0,  36,   9,  49])

In [26]:
np.std(squared)

144.0243035046516

In [27]:
np.mean(squared)

74.0

In [21]:
# # A common statistical operation on a dataset is centering. 
# This means to adjust the data such that the mean of the data is 0. 
# This is done by subtracting the mean from each data point. 
# Center the data set. See this link for more on centering.

In [189]:
centered = a - a.mean()
centered

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

In [190]:
np.mean(centered)

0.0

In [35]:
# Calculate the z-score for each data point. Recall that the z-score is given by:
# Z=(x−μ)/σ


In [39]:
σ = np.std(a)

In [40]:
μ = np.mean(a)

In [41]:
(a- μ)/ σ

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

In [192]:
# ## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
import math
# Use python's built in functionality/operators to determine the following:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

In [193]:
sum_of_a = sum(a)
sum_of_a

55

In [44]:
# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

In [45]:
min_of_a = min(a)
min_of_a

1

In [46]:
# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

In [47]:
max_of_a = max(a)
max_of_a

10

In [48]:
# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

In [101]:
count_of_a = len(a)
mean_of_a = (sum_of_a / count_of_a)
mean_of_a

5.5

In [53]:
# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all 
# the numbers in the above list together

In [104]:
product_of_a = math.prod(a)
product_of_a

# instructor answer
# product_of_a = 1
# for n in a:
#     product_of_a = product_of_a *= n

3628800

In [55]:
# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

In [118]:
squares_of_a = 0
for n in a:
    print(n**2)
    
# instructor answer
# squares_of_a = [n**2 for n in a]
# squares_of_a
# ***produces results in list format[]***

1
4
9
16
25
36
49
64
81
100


In [58]:
# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

In [90]:
odds_in_a = 0
for n in a:
    if (n % 2 ==1):
        print(n)

1
3
5
7
9


In [72]:
# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

In [140]:
evens_in_a = 0
for n in a:
    if (n % 2 ==0):
        print(n)

2
4
6
8
10


In [194]:
## What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.
b = [
    [3, 4, 5],
    [6, 7, 8]
]

matrix_b = np.array(b)

print(b)
print(matrix_b)


[[3, 4, 5], [6, 7, 8]]
[[3 4 5]
 [6 7 8]]


In [113]:
# # Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. 
# **Hint, you'll first need to make sure that the "b" variable is a numpy array**
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)
sum_of_b

33

In [127]:
sum_of_b = matrix_b.sum()
sum_of_b

33

In [120]:
# Exercise 2 - refactor the following to use numpy. 
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])
min_of_b

3

In [125]:
min_of_b = matrix_b.min()
min_of_b 

3

In [128]:
# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])
max_of_b

8

In [130]:
max_of_b = matrix_b.max()
max_of_b

8

In [131]:
# Exercise 4 - refactor the following using numpy to find the mean of b
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))
mean_of_b

5.5

In [133]:
mean_of_b = matrix_b.mean()
mean_of_b 

5.5

In [135]:
# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number
product_of_b

20160

In [137]:
product_of_b = matrix_b.prod()
product_of_b

20160

In [138]:
# Exercise 6 - refactor the following to use numpy to find the list of squares 
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)
squares_of_b

[9, 16, 25, 36, 49, 64]

In [143]:
squares_of_b = np.square(matrix_b)
squares_of_b

array([[ 9, 16, 25],
       [36, 49, 64]])

In [144]:
# Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)
odds_in_b 

[3, 5, 7]

In [145]:
odds_in_b = matrix_b[(matrix_b % 2 ==1)]
odds_in_b 

array([3, 5, 7])

In [146]:
# Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)
evens_in_b

[4, 6, 8]

In [147]:
evens_in_b = matrix_b[(matrix_b % 2 ==0)]
evens_in_b

array([4, 6, 8])

In [149]:
# Exercise 9 - print out the shape of the array b.
matrix_b.shape

(2, 3)

In [160]:
# Exercise 10 - transpose the array b.
matrix_b.transpose()

array([[3, 6],
       [4, 7],
       [5, 8]])

In [152]:
# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)
matrix_b.reshape(1,6)
# can use .flatten to make 1 dimensional array

array([[3, 4, 5, 6, 7, 8]])

In [153]:
# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)
matrix_b.reshape(6,1)

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [195]:
## Setup 3
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

# HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.

In [200]:
c = np.array(c)
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [156]:
# Exercise 1 - Find the min, max, sum, and product of c.
min_of_c = c.min()
max_of_c = c.max()
sum_of_c = c.sum()
product_of_c = c.prod()

In [157]:
# Exercise 2 - Determine the standard deviation of c.
std_of_c = c.std()
std_of_c

2.581988897471611

In [158]:
# Exercise 3 - Determine the variance of c.
var_of_c = c.var()
var_of_c

6.666666666666667

In [159]:
# Exercise 4 - Print out the shape of the array c
c.shape

(3, 3)

In [161]:
c.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [201]:
# Exercise 6 - Get the dot product of the array c with c. 
np.dot(c,c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [166]:
# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261


In [204]:
(c * c.T).sum()

261

In [ ]:
# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.


In [205]:
(c * c.T).prod()

131681894400

In [207]:
## Setup 4
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]



In [213]:
d = np.array(d)

In [217]:
# Exercise 1 - Find the sine of all the numbers in d
np.sin(d)


array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

In [218]:
# Exercise 2 - Find the cosine of all the numbers in d
np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

In [219]:
# Exercise 3 - Find the tangent of all the numbers in d
np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

In [220]:
# Exercise 4 - Find all the negative numbers in d
d[d<0]

array([-90, -30, -45, -45])

In [221]:
# Exercise 5 - Find all the positive numbers in d
d[d>0]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

In [222]:
# Exercise 6 - Return an array of only the unique numbers in d.
np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

In [223]:
# Exercise 7 - Determine how many unique numbers there are in d.
np.unique(d).size

11

In [224]:
# Exercise 8 - Print out the shape of d.
d.shape

(3, 6)

In [225]:
# Exercise 9 - Transpose and then print out the shape of d.
d.T.shape

(6, 3)

In [226]:
# Exercise 10 - Reshape d into an array of 9 x 2
d.reshape(9,2)

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])