In [3]:
import numpy as np

In [4]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [ ]:
# How many negative numbers are there?  --4

In [5]:
a[a <0]

array([-2, -1, -6, -7])

In [ ]:
# How many positive numbers are there?  --5

In [6]:
a[a>0]

array([ 4, 10, 12, 23,  3])

In [ ]:
# How many even positive numbers are there? --3

In [8]:
a[(a>0) & (a % 2 == 0)]

array([ 4, 10, 12])

In [9]:
# If you were to add 3 to each data point, how many positive numbers would there be? --5

In [14]:
new = a + 3

In [15]:
new[a>0]

array([ 7, 13, 15, 26,  6])

In [16]:
# If you squared each number, what would the new mean and standard deviation be?

In [24]:
squared = np.square(a)

In [25]:
squared

array([ 16, 100, 144, 529,   4,   1,   0,   0,   0,  36,   9,  49])

In [26]:
np.std(squared)

144.0243035046516

In [27]:
np.mean(squared)

74.0

In [21]:
# # A common statistical operation on a dataset is centering. 
# This means to adjust the data such that the mean of the data is 0. 
# This is done by subtracting the mean from each data point. 
# Center the data set. See this link for more on centering.

In [33]:
centered = a - 3

In [34]:
np.mean(centered)

0.0

In [35]:
# Calculate the z-score for each data point. Recall that the z-score is given by:
# Z=(x−μ)/σ


In [39]:
σ = np.std(a)

In [40]:
μ = np.mean(a)

In [41]:
(a- μ)/ σ

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])